# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: , addresses: 'Chicago' }, { name: , addresses: 'Copenhagen' }])
#   Mayor.create(name: , addresses: 'Emanuel', city: cities.first)
# WARNING: these seeds assume you have edited the devise config to allow for single letter passwords
#
# 
# uses this dictionary to generate random tags
load "#{Rails.root}/db/words.rb"

def gen_tag
  str = String.new
  len = rand(4) + 1
  for i in 1..len
    str += $words.sample + " "
  end
  return str
end

users = User.create(
  [
    { email: 'a@a.com', name: "Mr. Aardvark", password: "aaaaaaaa", password_confirmation: "aaaaaaaa"},
    { email: 'b@b.com', name: "Mr. Bear", password: "bbbbbbbb", password_confirmation: "bbbbbbbb"},
    { email: 'c@c.com', name: "Mr. Cat", password: "cccccccc", password_confirmation: "cccccccc"},
    { email: 'd@d.com', name: "Mr. Dog", password: "dddddddd", password_confirmation: "dddddddd"},
    { email: 'e@e.com', name: "Mr. Elephant", password: "eeeeeeee", password_confirmation: "eeeeeeee"},
    { email: 'f@f.com', name: "Mr. Fox", password: "ffffffff", password_confirmation: "ffffffff"},
    { email: 'g@g.com', name: "Mr. Gopher", password: "gggggggg", password_confirmation: "gggggggg"},
    { email: 'h@h.com', name: "Mr. Horse", password: "hhhhhhhh", password_confirmation: "hhhhhhhh"},
    { email: 'i@i.com', name: "Mr. Iguana", password: "iiiiiiii", password_confirmation: "iiiiiiii"},
    { email: 'j@j.com', name: "Mr. Jackrabbit", password: "jjjjjjjj", password_confirmation: "jjjjjjjj"},
    { email: 'k@k.com', name: "Mr. Kangaroo", password: "kkkkkkkk", password_confirmation: "kkkkkkkk"},
    { email: 'l@l.com', name: "Mr. Llama", password: "llllllll", password_confirmation: "llllllll"},
    { email: 'm@m.com', name: "Mr. Mouse", password: "mmmmmmmm", password_confirmation: "mmmmmmmm"},
    { email: 'n@n.com', name: "Mr. Numbat", password: "nnnnnnnn", password_confirmation: "nnnnnnnn"},
    { email: 'o@o.com', name: "Mr. Opossum", password: "oooooooo", password_confirmation: "oooooooo"},
    { email: 'p@p.com', name: "Mr. Peacock", password: "pppppppp", password_confirmation: "pppppppp"},
    { email: 'q@q.com', name: "Mr. Quail", password: "qqqqqqqq", password_confirmation: "qqqqqqqq"},
    { email: 'r@r.com', name: "Mr. Rabbit", password: "rrrrrrrr", password_confirmation: "rrrrrrrr"},
    { email: 's@s.com', name: "Mr. Snake", password: "ssssssss", password_confirmation: "ssssssss"},
    { email: 't@t.com', name: "Mr. Tiger", password: "tttttttt", password_confirmation: "tttttttt"},
    { email: 'u@u.com', name: "Mr. Urial", password: "uuuuuuuu", password_confirmation: "uuuuuuuu"},
    { email: 'v@v.com', name: "Mr. Vulture", password: "vvvvvvvv", password_confirmation: "vvvvvvvv"},
    { email: 'w@w.com', name: "Mr. Wombat", password: "wwwwwwww", password_confirmation: "wwwwwwww"},
    { email: 'x@x.com', name: "Mr. Xerox", password: "xxxxxxxx", password_confirmation: "xxxxxxxx"},
    { email: 'y@y.com', name: "Mr. Yak", password: "yyyyyyyy", password_confirmation: "yyyyyyyy"},
    { email: 'z@z.com', name: "Mr. Zebra", password: "zzzzzzzz", password_confirmation: "zzzzzzzz"},
  ]
)

businesscards = BusinessCard.create(
  [
    { name: "Mr. Aardvark", addresses: "1 West First Street, Chico CA 95926", pinterest: "f", user_id: 1 },
    { name: "Mr. Bear", addresses: "2 West First Street, Chico CA 95926", pinterest: "f", user_id: 2 },
    { name: "Mr. Cat", addresses: "3 West First Street, Chico CA 95926", pinterest: "f", user_id: 3 },
    { name: "Mr. Dog", addresses: "4 West First Street, Chico CA 95926", pinterest: "t", user_id: 4 },
    { name: "Mr. Elephant", addresses: "5 West First Street, Chico CA 95926", pinterest: "t", user_id: 5 },
    { name: "Mr. Fox", addresses: "6 West First Street, Chico CA 95926", pinterest: "f", user_id: 6 },
    { name: "Mr. Gopher", addresses: "7 West First Street, Chico CA 95926", pinterest: "f", user_id: 7 },
    { name: "Mr. Horse", addresses: "8 West First Street, Chico CA 95926", pinterest: "f", user_id: 8 },
    { name: "Mr. Iguana", addresses: "9 West First Street, Chico CA 95926", pinterest: "f", user_id: 9 },
    { name: "Mr. Jackrabbit", addresses: "10 West First Street, Chico CA 95926", pinterest: "f", user_id: 10 },
    { name: "Mr. Kangaroo", addresses: "11 West First Street, Chico CA 95926", pinterest: "f", user_id: 11 },
    { name: "Mr. Llama", addresses: "12 West First Street, Chico CA 95926", pinterest: "f", user_id: 12 },
    { name: "Mr. Mouse", addresses: "13 West First Street, Chico CA 95926", pinterest: "t", user_id: 13 },
    { name: "Mr. Numbat", addresses: "14 West First Street, Chico CA 95926", pinterest: "t", user_id: 14 },
    { name: "Mr. Opossum", addresses: "15 West First Street, Chico CA 95926", pinterest: "f", user_id: 15 },
    { name: "Mr. Peacock", addresses: "16 West First Street, Chico CA 95926", pinterest: "t", user_id: 16 },
    { name: "Mr. Quail", addresses: "17 West First Street, Chico CA 95926", pinterest: "f", user_id: 17 },
    { name: "Mr. Rabbit", addresses: "18 West First Street, Chico CA 95926", pinterest: "f", user_id: 18 },
    { name: "Mr. Snake", addresses: "19 West First Street, Chico CA 95926", pinterest: "f", user_id: 19 },
    { name: "Mr. Tiger", addresses: "20 West First Street, Chico CA 95926", pinterest: "t", user_id:20 },
    { name: "Mr. Urial", addresses: "21 West First Street, Chico CA 95926", pinterest: "t", user_id: 21 },
    { name: "Mr. Vulture", addresses: "22 West First Street, Chico CA 95926", pinterest: "f", user_id: 22 },
    { name: "Mr. Wombat", addresses: "23 West First Street, Chico CA 95926", pinterest: "f", user_id: 23 },
    { name: "Mr. Xerox", addresses: "24 West First Street, Chico CA 95926", pinterest: "f", user_id: 24 },
    { name: "Mr. Yak", addresses: "25 West First Street, Chico CA 95926", pinterest: "t", user_id: 25 },
    { name: "Mr. Zebra", addresses: "26 West First Street, Chico CA 95926", pinterest: "f", user_id: 26 },
    { name: "John Doe", addresses: "27 West First Street, Chico CA 95926", pinterest: "t", user_id: 14 },
    { name: "John Doe", addresses: "28 West First Street, Chico CA 95926", pinterest: "t", user_id: 3 },
    { name: "John Doe", addresses: "29 West First Street, Chico CA 95926", pinterest: "t", user_id: 25 },
    { name: "John Doe", addresses: "30 West First Street, Chico CA 95926", pinterest: "t", user_id: 7 },
    { name: "John Doe", addresses: "31 West First Street, Chico CA 95926", pinterest: "f", user_id: 24 },
    { name: "John Doe", addresses: "32 West First Street, Chico CA 95926", pinterest: "f", user_id: 11 },
    { name: "John Doe", addresses: "33 West First Street, Chico CA 95926", pinterest: "f", user_id: 15 },
    { name: "John Doe", addresses: "34 West First Street, Chico CA 95926", pinterest: "f", user_id: 5 },
    { name: "John Doe", addresses: "35 West First Street, Chico CA 95926", pinterest: "f", user_id: 12 },
    { name: "John Doe", addresses: "36 West First Street, Chico CA 95926", pinterest: "f", user_id: 13 },
    { name: "John Doe", addresses: "37 West First Street, Chico CA 95926", pinterest: "f", user_id: 1 },
    { name: "John Doe", addresses: "38 West First Street, Chico CA 95926", pinterest: "f", user_id: 17 },
    { name: "John Doe", addresses: "39 West First Street, Chico CA 95926", pinterest: "f", user_id: 23 },
    { name: "John Doe", addresses: "40 West First Street, Chico CA 95926", pinterest: "t", user_id: 8 },
    { name: "John Doe", addresses: "41 West First Street, Chico CA 95926", pinterest: "f", user_id: 16 },
    { name: "John Doe", addresses: "42 West First Street, Chico CA 95926", pinterest: "f", user_id: 13 },
    { name: "John Doe", addresses: "43 West First Street, Chico CA 95926", pinterest: "f", user_id: 15 },
    { name: "John Doe", addresses: "44 West First Street, Chico CA 95926", pinterest: "t", user_id: 8 },
    { name: "John Doe", addresses: "45 West First Street, Chico CA 95926", pinterest: "f", user_id: 23 },
    { name: "John Doe", addresses: "46 West First Street, Chico CA 95926", pinterest: "t", user_id: 11 },
    { name: "John Doe", addresses: "47 West First Street, Chico CA 95926", pinterest: "f", user_id: 5 },
    { name: "John Doe", addresses: "48 West First Street, Chico CA 95926", pinterest: "t", user_id: 8 },
    { name: "John Doe", addresses: "49 West First Street, Chico CA 95926", pinterest: "f", user_id: 17 },
    { name: "John Doe", addresses: "50 West First Street, Chico CA 95926", pinterest: "f", user_id: 7 },
    { name: "John Doe", addresses: "51 West First Street, Chico CA 95926", pinterest: "t", user_id: 2 },
    { name: "John Doe", addresses: "52 West First Street, Chico CA 95926", pinterest: "f", user_id: 17 },
    { name: "John Doe", addresses: "53 West First Street, Chico CA 95926", pinterest: "t", user_id: 12 },
    { name: "John Doe", addresses: "54 West First Street, Chico CA 95926", pinterest: "t", user_id: 10 },
    { name: "John Doe", addresses: "55 West First Street, Chico CA 95926", pinterest: "t", user_id: 22 },
    { name: "John Doe", addresses: "56 West First Street, Chico CA 95926", pinterest: "f", user_id: 23 },
    { name: "John Doe", addresses: "57 West First Street, Chico CA 95926", pinterest: "t", user_id: 4 },
    { name: "John Doe", addresses: "58 West First Street, Chico CA 95926", pinterest: "t", user_id: 17 },
    { name: "John Doe", addresses: "59 West First Street, Chico CA 95926", pinterest: "f", user_id: 2 },
    { name: "John Doe", addresses: "60 West First Street, Chico CA 95926", pinterest: "f", user_id: 9 },
    { name: "John Doe", addresses: "61 West First Street, Chico CA 95926", pinterest: "f", user_id: 13 },
    { name: "John Doe", addresses: "62 West First Street, Chico CA 95926", pinterest: "f", user_id: 20 },
    { name: "John Doe", addresses: "63 West First Street, Chico CA 95926", pinterest: "t", user_id: 18 },
    { name: "Jane Doe", addresses: "64 West First Street, Chico CA 95926", pinterest: "f", user_id: 12 },
    { name: "Jane Doe", addresses: "65 West First Street, Chico CA 95926", pinterest: "f", user_id: 16 },
    { name: "Jane Doe", addresses: "66 West First Street, Chico CA 95926", pinterest: "f", user_id: 14 },
    { name: "Jane Doe", addresses: "67 West First Street, Chico CA 95926", pinterest: "t", user_id: 14 },
    { name: "Jane Doe", addresses: "68 West First Street, Chico CA 95926", pinterest: "f", user_id: 23 },
    { name: "Jane Doe", addresses: "69 West First Street, Chico CA 95926", pinterest: "t", user_id: 17 },
    { name: "Jane Doe", addresses: "70 West First Street, Chico CA 95926", pinterest: "f", user_id: 10 },
    { name: "Jane Doe", addresses: "71 West First Street, Chico CA 95926", pinterest: "t", user_id: 1 },
    { name: "Jane Doe", addresses: "72 West First Street, Chico CA 95926", pinterest: "f", user_id: 1 },
    { name: "Jane Doe", addresses: "73 West First Street, Chico CA 95926", pinterest: "f", user_id: 18 },
    { name: "Jane Doe", addresses: "74 West First Street, Chico CA 95926", pinterest: "f", user_id: 23 },
    { name: "Jane Doe", addresses: "75 West First Street, Chico CA 95926", pinterest: "f", user_id: 15 },
    { name: "Jane Doe", addresses: "76 West First Street, Chico CA 95926", pinterest: "f", user_id: 19 },
    { name: "Jane Doe", addresses: "77 West First Street, Chico CA 95926", pinterest: "t", user_id: 3 },
    { name: "Jane Doe", addresses: "78 West First Street, Chico CA 95926", pinterest: "f", user_id: 21 },
    { name: "Jane Doe", addresses: "79 West First Street, Chico CA 95926", pinterest: "t", user_id: 17 },
    { name: "Jane Doe", addresses: "80 West First Street, Chico CA 95926", pinterest: "f", user_id: 6 },
    { name: "Jack Smith", addresses: "81 West First Street, Chico CA 95926", pinterest: "f", user_id: 2 },
    { name: "Jack Smith", addresses: "82 West First Street, Chico CA 95926", pinterest: "f", user_id: 1 },
    { name: "Jack Smith", addresses: "83 West First Street, Chico CA 95926", pinterest: "t", user_id: 24 },
    { name: "Jack Smith", addresses: "84 West First Street, Chico CA 95926", pinterest: "t", user_id: 16 },
    { name: "Jack Smith", addresses: "85 West First Street, Chico CA 95926", pinterest: "f", user_id: 3 },
    { name: "Jack Smith", addresses: "86 West First Street, Chico CA 95926", pinterest: "f", user_id: 3 },
    { name: "Jack Smith", addresses: "87 West First Street, Chico CA 95926", pinterest: "f", user_id: 8 },
    { name: "Jack Smith", addresses: "88 West First Street, Chico CA 95926", pinterest: "t", user_id: 8 },
    { name: "Jack Smith", addresses: "89 West First Street, Chico CA 95926", pinterest: "f", user_id: 22 },
    { name: "Jack Smith", addresses: "90 West First Street, Chico CA 95926", pinterest: "f", user_id: 18 },
    { name: "Jack Smith", addresses: "91 West First Street, Chico CA 95926", pinterest: "t", user_id: 13 },
    { name: "Jack Smith", addresses: "92 West First Street, Chico CA 95926", pinterest: "f", user_id: 14 },
    { name: "Jack Smith", addresses: "93 West First Street, Chico CA 95926", pinterest: "f", user_id: 26 },
    { name: "Jack Smith", addresses: "94 West First Street, Chico CA 95926", pinterest: "t", user_id: 11 },
    { name: "Jack Smith", addresses: "95 West First Street, Chico CA 95926", pinterest: "f", user_id: 17 },
    { name: "Jack Smith", addresses: "96 West First Street, Chico CA 95926", pinterest: "f", user_id: 24 },
    { name: "Jack Smith", addresses: "97 West First Street, Chico CA 95926", pinterest: "t", user_id: 10 },
    { name: "Jack Smith", addresses: "98 West First Street, Chico CA 95926", pinterest: "f", user_id: 11 },
    { name: "Jack Smith", addresses: "99 West First Street, Chico CA 95926", pinterest: "t", user_id: 20 },
    { name: "Arnold Palmer", addresses: "100 West First Street, Chico CA 95926", pinterest: "f", user_id: 25 },
    { name: "Arnold Palmer", addresses: "101 West First Street, Chico CA 95926", pinterest: "f", user_id: 1 },
    { name: "Arnold Palmer", addresses: "102 West First Street, Chico CA 95926", pinterest: "t", user_id: 2 },
    { name: "Arnold Palmer", addresses: "103 West First Street, Chico CA 95926", pinterest: "f", user_id: 8 },
    { name: "Arnold Palmer", addresses: "104 West First Street, Chico CA 95926", pinterest: "t", user_id: 9 },
    { name: "Arnold Palmer", addresses: "105 West First Street, Chico CA 95926", pinterest: "f", user_id: 17 },
    { name: "Arnold Palmer", addresses: "106 West First Street, Chico CA 95926", pinterest: "f", user_id: 15 },
    { name: "Arnold Palmer", addresses: "107 West First Street, Chico CA 95926", pinterest: "f", user_id: 14 },
    { name: "Arnold Palmer", addresses: "108 West First Street, Chico CA 95926", pinterest: "f", user_id: 20 },
    { name: "Arnold Palmer", addresses: "109 West First Street, Chico CA 95926", pinterest: "t", user_id: 13 },
    { name: "Arnold Palmer", addresses: "110 West First Street, Chico CA 95926", pinterest: "t", user_id: 7 },
    { name: "Arnold Palmer", addresses: "111 West First Street, Chico CA 95926", pinterest: "f", user_id: 23 },
    { name: "Arnold Palmer", addresses: "112 West First Street, Chico CA 95926", pinterest: "f", user_id: 23 },
    { name: "Arnold Palmer", addresses: "113 West First Street, Chico CA 95926", pinterest: "t", user_id: 3 },
    { name: "Arnold Palmer", addresses: "114 West First Street, Chico CA 95926", pinterest: "f", user_id: 16 },
    { name: "Arnold Palmer", addresses: "115 West First Street, Chico CA 95926", pinterest: "f", user_id: 9 },
    { name: "Arnold Palmer", addresses: "116 West First Street, Chico CA 95926", pinterest: "t", user_id: 22 },
    { name: "Arnold Palmer", addresses: "117 West First Street, Chico CA 95926", pinterest: "f", user_id: 21 },
    { name: "Arnold Palmer", addresses: "118 West First Street, Chico CA 95926", pinterest: "f", user_id: 20 },
    { name: "Arnold Palmer", addresses: "119 West First Street, Chico CA 95926", pinterest: "f", user_id: 12 },
    { name: "Arnold Palmer", addresses: "120 West First Street, Chico CA 95926", pinterest: "t", user_id: 7 },
    { name: "Arnold Palmer", addresses: "121 West First Street, Chico CA 95926", pinterest: "f", user_id: 5 },
    { name: "Kevin Perkins", addresses: "122 West First Street, Chico CA 95926", pinterest: "t", user_id: 8 },
    { name: "Kevin Perkins", addresses: "123 West First Street, Chico CA 95926", pinterest: "f", user_id: 1 },
    { name: "Kevin Perkins", addresses: "124 West First Street, Chico CA 95926", pinterest: "t", user_id: 9 },
    { name: "Kevin Perkins", addresses: "125 West First Street, Chico CA 95926", pinterest: "t", user_id: 8 },
    { name: "Kevin Perkins", addresses: "126 West First Street, Chico CA 95926", pinterest: "t", user_id: 18 },
    { name: "Kevin Perkins", addresses: "127 West First Street, Chico CA 95926", pinterest: "t", user_id: 20 },
    { name: "Kevin Perkins", addresses: "128 West First Street, Chico CA 95926", pinterest: "f", user_id: 11 },
    { name: "Kevin Perkins", addresses: "129 West First Street, Chico CA 95926", pinterest: "f", user_id: 23 },
    { name: "Kevin Perkins", addresses: "130 West First Street, Chico CA 95926", pinterest: "f", user_id: 19 },
    { name: "Kevin Perkins", addresses: "131 West First Street, Chico CA 95926", pinterest: "f", user_id: 19 },
    { name: "Kevin Perkins", addresses: "132 West First Street, Chico CA 95926", pinterest: "f", user_id: 17 },
    { name: "Kevin Perkins", addresses: "133 West First Street, Chico CA 95926", pinterest: "f", user_id: 17 },
    { name: "Kevin Perkins", addresses: "134 West First Street, Chico CA 95926", pinterest: "f", user_id: 19 },
    { name: "Kevin Perkins", addresses: "135 West First Street, Chico CA 95926", pinterest: "f", user_id: 15 },
    { name: "Tyson Henry", addresses: "136 West First Street, Chico CA 95926", pinterest: "f", user_id: 7 },
    { name: "Tyson Henry", addresses: "137 West First Street, Chico CA 95926", pinterest: "f", user_id: 23 },
    { name: "Tyson Henry", addresses: "138 West First Street, Chico CA 95926", pinterest: "t", user_id: 14 },
    { name: "Tyson Henry", addresses: "139 West First Street, Chico CA 95926", pinterest: "t", user_id: 17 },
    { name: "Tyson Henry", addresses: "140 West First Street, Chico CA 95926", pinterest: "t", user_id: 14 },
    { name: "Tyson Henry", addresses: "141 West First Street, Chico CA 95926", pinterest: "t", user_id: 12 },
    { name: "Tyson Henry", addresses: "142 West First Street, Chico CA 95926", pinterest: "f", user_id: 4 },
    { name: "Tyson Henry", addresses: "143 West First Street, Chico CA 95926", pinterest: "t", user_id: 23 },
    { name: "Tyson Henry", addresses: "144 West First Street, Chico CA 95926", pinterest: "t", user_id: 2 },
    { name: "Tyson Henry", addresses: "145 West First Street, Chico CA 95926", pinterest: "f", user_id: 18 },
    { name: "Tyson Henry", addresses: "146 West First Street, Chico CA 95926", pinterest: "t", user_id: 2 },
    { name: "Tyson Henry", addresses: "147 West First Street, Chico CA 95926", pinterest: "f", user_id: 14 },
    { name: "Tyson Henry", addresses: "148 West First Street, Chico CA 95926", pinterest: "f", user_id: 1 },
    { name: "Tyson Henry", addresses: "149 West First Street, Chico CA 95926", pinterest: "f", user_id: 5 },
    { name: "Tyson Henry", addresses: "150 West First Street, Chico CA 95926", pinterest: "t", user_id: 7 },
    { name: "Tyson Henry", addresses: "151 West First Street, Chico CA 95926", pinterest: "f", user_id: 21 },
    { name: "Tyson Henry", addresses: "152 West First Street, Chico CA 95926", pinterest: "t", user_id: 15 },
    { name: "Tyson Henry", addresses: "153 West First Street, Chico CA 95926", pinterest: "f", user_id: 3 },
    { name: "Tyson Henry", addresses: "154 West First Street, Chico CA 95926", pinterest: "f", user_id: 18 },
    { name: "Tyson Henry", addresses: "155 West First Street, Chico CA 95926", pinterest: "f", user_id: 2 },
    { name: "Tyson Henry", addresses: "156 West First Street, Chico CA 95926", pinterest: "t", user_id: 20 },
    { name: "Tyson Henry", addresses: "157 West First Street, Chico CA 95926", pinterest: "t", user_id: 11 },
    { name: "Tyson Henry", addresses: "158 West First Street, Chico CA 95926", pinterest: "f", user_id: 24 },
    { name: "Tyson Henry", addresses: "159 West First Street, Chico CA 95926", pinterest: "t", user_id: 15 },
    { name: "Tyson Henry", addresses: "160 West First Street, Chico CA 95926", pinterest: "f", user_id: 3 },
    { name: "Tyson Henry", addresses: "161 West First Street, Chico CA 95926", pinterest: "t", user_id: 23 },
    { name: "Tyson Henry", addresses: "162 West First Street, Chico CA 95926", pinterest: "t", user_id: 22 },
    { name: "Rick Sanchez", addresses: "163 West First Street, Chico CA 95926", pinterest: "f", user_id: 24 },
    { name: "Rick Sanchez", addresses: "164 West First Street, Chico CA 95926", pinterest: "f", user_id: 18 },
    { name: "Rick Sanchez", addresses: "165 West First Street, Chico CA 95926", pinterest: "f", user_id: 18 },
    { name: "Rick Sanchez", addresses: "166 West First Street, Chico CA 95926", pinterest: "t", user_id: 24 },
    { name: "Rick Sanchez", addresses: "167 West First Street, Chico CA 95926", pinterest: "f", user_id: 13 },
    { name: "Rick Sanchez", addresses: "168 West First Street, Chico CA 95926", pinterest: "f", user_id: 4 },
    { name: "Rick Sanchez", addresses: "169 West First Street, Chico CA 95926", pinterest: "t", user_id: 20 },
    { name: "Rick Sanchez", addresses: "170 West First Street, Chico CA 95926", pinterest: "f", user_id: 11 },
    { name: "Rick Sanchez", addresses: "171 West First Street, Chico CA 95926", pinterest: "f", user_id: 1 },
    { name: "Rick Sanchez", addresses: "172 West First Street, Chico CA 95926", pinterest: "f", user_id: 13 },
    { name: "Rick Sanchez", addresses: "173 West First Street, Chico CA 95926", pinterest: "t", user_id: 5 },
    { name: "Rick Sanchez", addresses: "174 West First Street, Chico CA 95926", pinterest: "f", user_id: 21 },
    { name: "Rick Sanchez", addresses: "175 West First Street, Chico CA 95926", pinterest: "t", user_id: 11 },
    { name: "Rick Sanchez", addresses: "176 West First Street, Chico CA 95926", pinterest: "t", user_id: 3 },
    { name: "Rick Sanchez", addresses: "177 West First Street, Chico CA 95926", pinterest: "f", user_id: 2 },
    { name: "Rick Sanchez", addresses: "178 West First Street, Chico CA 95926", pinterest: "f", user_id: 21 },
    { name: "Rick Sanchez", addresses: "179 West First Street, Chico CA 95926", pinterest: "t", user_id: 21 },
    { name: "Rick Sanchez", addresses: "180 West First Street, Chico CA 95926", pinterest: "t", user_id: 5 },
    { name: "Rick Sanchez", addresses: "181 West First Street, Chico CA 95926", pinterest: "t", user_id: 13 },
    { name: "Rick Sanchez", addresses: "182 West First Street, Chico CA 95926", pinterest: "t", user_id: 25 },
    { name: "Rick Sanchez", addresses: "183 West First Street, Chico CA 95926", pinterest: "t", user_id: 20 },
    { name: "Rick Sanchez", addresses: "184 West First Street, Chico CA 95926", pinterest: "f", user_id: 18 },
    { name: "Rick Sanchez", addresses: "185 West First Street, Chico CA 95926", pinterest: "f", user_id: 25 },
    { name: "Rick Sanchez", addresses: "186 West First Street, Chico CA 95926", pinterest: "f", user_id: 9 },
    { name: "Jan Michael Vincent", addresses: "187 West First Street, Chico CA 95926", pinterest: "f", user_id: 10 },
    { name: "Jan Michael Vincent", addresses: "188 West First Street, Chico CA 95926", pinterest: "f", user_id: 12 },
    { name: "Jan Michael Vincent", addresses: "189 West First Street, Chico CA 95926", pinterest: "f", user_id: 7 },
    { name: "Jan Michael Vincent", addresses: "190 West First Street, Chico CA 95926", pinterest: "t", user_id: 9 },
    { name: "Jan Michael Vincent", addresses: "191 West First Street, Chico CA 95926", pinterest: "f", user_id: 6 },
    { name: "Jan Michael Vincent", addresses: "192 West First Street, Chico CA 95926", pinterest: "f", user_id: 26 },
    { name: "Jan Michael Vincent", addresses: "193 West First Street, Chico CA 95926", pinterest: "f", user_id: 12 },
    { name: "Jan Michael Vincent", addresses: "194 West First Street, Chico CA 95926", pinterest: "t", user_id: 9 },
    { name: "Jan Michael Vincent", addresses: "195 West First Street, Chico CA 95926", pinterest: "f", user_id: 10 },
    { name: "Jan Michael Vincent", addresses: "196 West First Street, Chico CA 95926", pinterest: "f", user_id: 21 },
    { name: "Jan Michael Vincent", addresses: "197 West First Street, Chico CA 95926", pinterest: "t", user_id: 19 },
    { name: "Jan Michael Vincent", addresses: "198 West First Street, Chico CA 95926", pinterest: "f", user_id: 25 },
    { name: "Jan Michael Vincent", addresses: "199 West First Street, Chico CA 95926", pinterest: "t", user_id: 25 },
    { name: "Jan Michael Vincent", addresses: "200 West First Street, Chico CA 95926", pinterest: "f", user_id: 1 },
    { name: "Jan Michael Vincent", addresses: "201 West First Street, Chico CA 95926", pinterest: "f", user_id: 21 },
    { name: "Jan Michael Vincent", addresses: "202 West First Street, Chico CA 95926", pinterest: "f", user_id: 25 },
    { name: "Jan Michael Vincent", addresses: "203 West First Street, Chico CA 95926", pinterest: "f", user_id: 9 },
    { name: "Jan Michael Vincent", addresses: "204 West First Street, Chico CA 95926", pinterest: "f", user_id: 21 },
    { name: "Jan Michael Vincent", addresses: "205 West First Street, Chico CA 95926", pinterest: "f", user_id: 20 },
    { name: "Jan Michael Vincent", addresses: "206 West First Street, Chico CA 95926", pinterest: "t", user_id: 8 }
  ]
)

businesscards.each do |businesscard|

  # create access objects for current businesscard
    user_indexes = Array.new
    size = 3 + rand(6)
    for i in 0..size
      while (user_indexes[i] = (rand 25) + 1) == businesscard.user_id
      end
    end
    user_indexes.uniq!
    user_indexes.each do |user_id|
#      businesscardUser.create(user_id: user_id, businesscard_id: businesscard.id)
        for i in 0..rand(4)
            random_tag_string = gen_tag
            Tag.create(businesscard_id: businesscard.id, text: random_tag_string, user_id: user_id)
        end
    end

  # create tags

end
